services:
  sitecore-genai-frontend:
    container_name: sitecore_genai_frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - VITE_DOMAIN=http://localhost:5173
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules